CREATE TABLE IF NOT EXISTS roles (
    id INT UNSIGNED AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    creado_en DATETIME DEFAULT NOW(),
    actualizado_en DATETIME DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id)
);

