CREATE TABLE IF NOT EXISTS menues(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    menu VARCHAR(60) NOT NULL,
    descripcion VARCHAR(255),
    precio FLOAT NOT NULL,
    descuento BOOLEAN DEFAULT 0,
    estado BOOLEAN DEFAULT 1,
    creado_el DATETIME DEFAULT NOW(),
    actualizado_el DATETIME DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id)
);