CREATE TABLE IF NOT EXISTS pedidos(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    mesa_id INT UNSIGNED NULL DEFAULT NULL,
    mozo_id INT UNSIGNED NULL DEFAULT NULL,
    direccion VARCHAR(60) NULL DEFAULT NULL,
    estado VARCHAR(10) DEFAULT "EN CURSO",
    creado_el DATETIME DEFAULT NOW(),
    actualizado_el DATETIME DEFAULT NOW() ON UPDATE NOW(),
    FOREIGN KEY (mozo_id) REFERENCES usuarios(id),
    FOREIGN KEY (mesa_id) REFERENCES mesas(id),
    PRIMARY KEY (id)
);